// ╔═══════════════════════════════════════╗
// ║   fun-trivia.js — Ruby-Hoshino-Bot    ║
// ║   Plugin: Trivia (Fix Economía)       ║
// ╚═══════════════════════════════════════╝

let triviaActiva = {}

var handler = async (m, { conn, usedPrefix, command }) => {
    let chatId = m.chat

        if (chatId in triviaActiva) {
                return conn.reply(m.chat,
                            `⏳ *¡Ya hay una trivia activa!*\nResponde con *A, B, C* o *D*`,
                                        m
                                                )
                                                    }

                                                        let pregunta = pickRandom(global.triviaPreguntas)
                                                            let letras = ['A', 'B', 'C', 'D']
                                                                let moneda = global.moneda || 'Zenis'
                                                                    
                                                                        let opcionesTexto = pregunta.opciones
                                                                                .map((opt, i) => `│ 🔘 *${letras[i]})* ${opt}`)
                                                                                        .join('\n')

                                                                                            let mensajeTrivia = `╭──〔 🧠 TRIVIA RUBY ❀ 〕
                                                                                            │ ❓ *Pregunta »* ${pregunta.pregunta}
                                                                                            │
                                                                                            ${opcionesTexto}
                                                                                            │
                                                                                            │ ⏱️ *Tiempo »* 30 segundos
                                                                                            │ 🎁 *Premio »* 50 XP | 10 ${moneda}
                                                                                            ╰───────────────────
                                                                                            │ 📌 *Responde con la letra correcta.*`

                                                                                                await conn.reply(m.chat, mensajeTrivia, m)

                                                                                                    triviaActiva[chatId] = {
                                                                                                            pregunta,
                                                                                                                    timeout: setTimeout(async () => {
                                                                                                                                if (chatId in triviaActiva) {
                                                                                                                                                let correcta = triviaActiva[chatId].pregunta
                                                                                                                                                                delete triviaActiva[chatId]
                                                                                                                                                                                await conn.reply(m.chat,
                                                                                                                                                                                                    `╭──〔 ⏰ TIEMPO AGOTADO 〕\n│ La respuesta correcta era:\n│ *${correcta.respuesta}) ${correcta.opciones[letras.indexOf(correcta.respuesta)]}*\n╰───────────────────`,
                                                                                                                                                                                                                        m
                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                            }, 30000)
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                handler.before = async function (m, { conn }) {
                                                                                                                                                                                                                                                                    let chatId = m.chat
                                                                                                                                                                                                                                                                        if (!(chatId in triviaActiva)) return false
                                                                                                                                                                                                                                                                            if (!m.text) return false

                                                                                                                                                                                                                                                                                let respuesta = m.text.trim().toUpperCase()
                                                                                                                                                                                                                                                                                    let letrasValidas = ['A', 'B', 'C', 'D']
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                            if (!letrasValidas.includes(respuesta) || respuesta.length !== 1) return false

                                                                                                                                                                                                                                                                                                let trivia = triviaActiva[chatId]
                                                                                                                                                                                                                                                                                                    clearTimeout(trivia.timeout)
                                                                                                                                                                                                                                                                                                        delete triviaActiva[chatId]

                                                                                                                                                                                                                                                                                                            let letras = ['A', 'B', 'C', 'D']
                                                                                                                                                                                                                                                                                                                let respuestaCorrecta = trivia.pregunta.respuesta
                                                                                                                                                                                                                                                                                                                    let textoRespuesta = trivia.pregunta.opciones[letras.indexOf(respuestaCorrecta)]
                                                                                                                                                                                                                                                                                                                        let moneda = global.moneda || 'Zenis'

                                                                                                                                                                                                                                                                                                                            if (respuesta === respuestaCorrecta) {
                                                                                                                                                                                                                                                                                                                                    let xpGanado = 500000000
                                                                                                                                                                                                                                                                                                                                            let coinsGanados = 500000000000
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                            // --- SISTEMA DE GUARDADO ROBUSTO ---
                                                                                                                                                                                                                                                                                                                                                                    if (global.db && global.db.data && global.db.data.users) {
                                                                                                                                                                                                                                                                                                                                                                                let user = global.db.data.users[m.sender]
                                                                                                                                                                                                                                                                                                                                                                                            if (user) {
                                                                                                                                                                                                                                                                                                                                                                                                            user.exp = (user.exp || 0) + xpGanado
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                            // Intentamos en todas las posibles variables de economía del bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                            user.coin = (user.coin || 0) + coinsGanados   // Dinero en mano (Ruby Bot)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            user.bank = (user.bank || 0) + coinsGanados   // Dinero en banco
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (user.money !== undefined) user.money = (user.money || 0) + coinsGanados
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Forzar guardado en disco
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (typeof global.db.write === 'function') await global.db.write()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await conn.reply(m.chat,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `╭──〔 🎉 ¡CORRECTO! 〕
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │ ✅ La respuesta es: *${respuestaCorrecta}) ${textoRespuesta}*
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │ 🏆 *GANASTE:*
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │ ⭐ +${xpGanado} XP
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │ 🪙 +${coinsGanados} ${moneda} (En mano)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │ 🏦 +${coinsGanados} ${moneda} (En banco)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ╰───────────────────`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            m
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await conn.reply(m.chat,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `╭──〔 ❌ ¡INCORRECTO! 〕
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │ La respuesta correcta era:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │ *${respuestaCorrecta}) ${textoRespuesta}*
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ╰───────────────────`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            m
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            handler.help = ['trivia']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            handler.tags = ['fun']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            handler.command = /^(trivia|preguntados|quiz)$/i

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            handler.group = false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            handler.register = false

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default handler

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function pickRandom(list) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return list[Math.floor(list.length * Math.random())]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                global.triviaPreguntas = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pregunta: "¿Cuál es el planeta más grande del sistema solar?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    opciones: ["Marte", "Saturno", "Júpiter", "Urano"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            respuesta: "C"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pregunta: "¿Qué gas necesitan los humanos para respirar?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    opciones: ["Dióxido de carbono", "Nitrógeno", "Hidrógeno", "Oxígeno"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            respuesta: "D"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pregunta: "¿Cuántos huesos tiene el cuerpo humano adulto?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    opciones: ["206", "300", "150", "250"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            respuesta: "A"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pregunta: "¿Quién pintó la Mona Lisa?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    opciones: ["Van Gogh", "Da Vinci", "Picasso", "Monet"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            respuesta: "B"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pregunta: "¿Cuál es el océano más grande del mundo?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    opciones: ["Atlántico", "Índico", "Pacífico", "Ártico"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            respuesta: "C"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pregunta: "¿Cuál es el río más largo del mundo?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    opciones: ["Amazonas", "Nilo", "Yangtsé", "Misisipi"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            respuesta: "B"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log('✅ Plugin fun-trivia.js cargado (Fix Economía y DB)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                